"""
Mismatch Pseudoword Selector — subset matching for the Stim2 mismatch condition
=================================================================================
The real-word "mismatch" condition pairs some Stim1 words with a same-length,
~1-letter-different real-word foil (the "Mismatch Stim 2" column). Only a
subset of Stim1 rows are used this way. The pseudoword condition needs the
same number of mismatch trials, drawn from the pool of Pseudoword2 items
(each itself a 1-letter-different foil of Pseudoword1, generated by
second_pseudowords.py) — but *which* subset of the pool should be used?

This script treats the real-word Mismatch Stim2 set as the target
distribution (its PTAN/PTAF/OTAN/OTAF means) and searches the larger pool of
candidate Pseudoword2 items for the subset, equal in size to the real-word
mismatch set, whose own PTAN/PTAF/OTAN/OTAF means most closely match the
target — verified with two-tailed independent t-tests on each measure.

Because the four measures live on very different numeric scales (PTAF values
are much larger than PTAN/OTAN), raw mean differences are not comparable
across measures. Instead each measure's mismatch is expressed as a
standardized mean difference (Cohen's d, using the pooled SD of the two
groups being compared for that measure) before being combined into a single
composite score. Since sample sizes are fixed across candidate subsets,
minimizing |d| for a measure is equivalent to maximizing that measure's
t-test p-value, so this composite score directly captures both the "small
mean differences" and "high p-values" goals the matching aims for.

Search strategy: simulated annealing over which candidates are included in
the subset (swap-one-in-one-out moves), with many random restarts, keeping
the best-scoring subset found across the whole search. This is far more
effective than pure random subset sampling given the combinatorial pool size
(50 choose 25 is astronomically large), while still being simple to reason
about and reproduce (given a seed).

USAGE
-----
    python match_mismatch_pseudowords.py \\
        --input      data/workshopping.csv \\
        --output     data/mismatch_pseudowords_selected.csv \\
        --restarts   200 \\
        --steps      4000 \\
        --seed       42
"""

import argparse
import csv
import math
import random
from dataclasses import dataclass

import numpy as np
from rich.console import Console
from rich.progress import BarColumn, Progress, TaskProgressColumn, TextColumn, TimeElapsedColumn
from scipy import stats

_console = Console()

MEASURES = ("PTAN", "PTAF", "OTAN", "OTAF")


@dataclass
class Candidate:
    stim1: str
    pseudoword1: str
    pseudoword2: str
    stats: dict  # measure -> float


def load_data(path: str):
    """
    Returns (target, pool):
      target — dict measure -> np.array of real-word Mismatch Stim2 values
      pool   — list[Candidate] of all rows with a Pseudoword2 value
    """
    with open(path, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    valid = [r for r in rows if (r.get("Stim1") or "").strip() and (r.get("Word_PTAN") or "").strip()]

    target_rows = [r for r in valid if (r.get("Mismatch Stim 2") or "").strip()]
    target = {m: np.array([float(r[m]) for r in target_rows]) for m in MEASURES}

    pool = []
    for r in valid:
        pw2 = (r.get("Pseudoword2") or "").strip()
        if not pw2:
            continue
        pool.append(Candidate(
            stim1=r["Stim1"],
            pseudoword1=r.get("Pseudoword1", ""),
            pseudoword2=pw2,
            stats={m: float(r[f"Pseudoword2_{m}"]) for m in MEASURES},
        ))

    if not target_rows:
        raise SystemExit("ERROR: no rows with a 'Mismatch Stim 2' value found.")
    if len(pool) < len(target_rows):
        raise SystemExit(
            f"ERROR: candidate pool ({len(pool)}) smaller than target set ({len(target_rows)})."
        )

    print(f"Real-word Mismatch Stim2 (target) set: {len(target_rows)} items")
    print(f"Candidate Pseudoword2 pool: {len(pool)} items")
    return target, pool


def cohens_d_and_p(sample: np.ndarray, target: np.ndarray) -> tuple[float, float]:
    """
    Cohen's d (pooled-SD standardized mean difference) and the two-tailed
    independent-samples t-test p-value for sample vs. target. Since our
    candidate subsets are always the same size as the target set (n1 == n2),
    t reduces to d / sqrt(2/n), letting both be computed from one pooled SD.
    """
    n1, n2 = len(sample), len(target)
    v1, v2 = sample.var(ddof=1), target.var(ddof=1)
    pooled_sd = math.sqrt(((n1 - 1) * v1 + (n2 - 1) * v2) / (n1 + n2 - 2))
    if pooled_sd == 0:
        return 0.0, 1.0
    d = (sample.mean() - target.mean()) / pooled_sd
    t = d / math.sqrt(1 / n1 + 1 / n2)
    p = 2 * stats.t.sf(abs(t), n1 + n2 - 2)
    return float(d), float(p)


def score_subset(pool_stats: dict, indices: np.ndarray, target: dict):
    """
    pool_stats: measure -> full np.array over the whole pool (indexed like `pool`)
    indices: array of pool indices making up the candidate subset

    Returns (composite_score, d_by_measure, p_by_measure) — lower composite is better.
    """
    d_by_measure = {}
    p_by_measure = {}
    for m in MEASURES:
        sample = pool_stats[m][indices]
        d_by_measure[m], p_by_measure[m] = cohens_d_and_p(sample, target[m])
    composite = sum(d * d for d in d_by_measure.values())
    return composite, d_by_measure, p_by_measure


def simulated_annealing(
    pool_stats: dict, n_pool: int, k: int, target: dict,
    n_restarts: int, n_steps: int, rng: random.Random,
) -> tuple[np.ndarray, float, dict, dict]:
    if n_restarts < 1:
        raise ValueError("n_restarts must be >= 1")

    best_indices: np.ndarray | None = None
    best_score = float("inf")
    best_d: dict | None = None
    best_p: dict | None = None

    all_indices = list(range(n_pool))

    with Progress(
        TextColumn("[bold cyan]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        TimeElapsedColumn(),
        console=_console,
    ) as progress:
        task = progress.add_task("Searching for best-matched subset…", total=n_restarts)

        for restart in range(n_restarts):
            current = set(rng.sample(all_indices, k))
            not_current = set(all_indices) - current
            current_arr = np.array(sorted(current))
            current_score, current_d, current_p = score_subset(pool_stats, current_arr, target)

            t0, t_end = 1.0, 1e-4
            for step in range(n_steps):
                temp = t0 * (t_end / t0) ** (step / max(1, n_steps - 1))

                out_candidate = rng.choice(tuple(current))
                in_pick = rng.choice(tuple(not_current))

                proposal = (current - {out_candidate}) | {in_pick}
                proposal_arr = np.array(sorted(proposal))
                proposal_score, proposal_d, proposal_p = score_subset(pool_stats, proposal_arr, target)

                delta = proposal_score - current_score
                if delta < 0 or rng.random() < math.exp(-delta / temp):
                    current = proposal
                    not_current = (not_current - {in_pick}) | {out_candidate}
                    current_arr = proposal_arr
                    current_score, current_d, current_p = proposal_score, proposal_d, proposal_p

            if current_score < best_score:
                best_score = current_score
                best_indices = current_arr
                best_d, best_p = current_d, current_p

            progress.update(task, advance=1,
                             description=f"Searching… best composite score so far: {best_score:.4f}")

    assert best_indices is not None and best_d is not None and best_p is not None
    return best_indices, best_score, best_d, best_p


def run(input_path: str, output_path: str, n_restarts: int, n_steps: int, seed: int) -> None:
    rng = random.Random(seed)

    target, pool = load_data(input_path)
    k = len(target[MEASURES[0]])
    n_pool = len(pool)

    pool_stats = {m: np.array([c.stats[m] for c in pool]) for m in MEASURES}

    print(f"\nSearching for the {k}-item subset (of {n_pool} candidates) that best matches "
          f"the real-word mismatch set on PTAN/PTAF/OTAN/OTAF…")
    print(f"  {n_restarts} restarts x {n_steps} annealing steps, seed={seed}\n")

    best_indices, best_score, best_d, best_p = simulated_annealing(
        pool_stats, n_pool, k, target, n_restarts, n_steps, rng
    )

    selected = [pool[i] for i in sorted(best_indices)]
    unselected = [pool[i] for i in range(n_pool) if i not in set(best_indices.tolist())]

    target_means = {m: target[m].mean() for m in MEASURES}
    selected_means = {m: pool_stats[m][best_indices].mean() for m in MEASURES}

    all_nonsignificant = all(p >= 0.05 for p in best_p.values())

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)
    print(f"{'Measure':<8}{'Real mean':>12}{'Pseudo mean':>14}{'Cohen d':>10}{'t-test p':>12}")
    for m in MEASURES:
        print(f"{m:<8}{target_means[m]:>12.4f}{selected_means[m]:>14.4f}"
              f"{best_d[m]:>10.4f}{best_p[m]:>12.4f}")
    print(f"\nComposite score (sum of squared Cohen's d): {best_score:.4f}")
    print(f"All four measures non-significant (p ≥ 0.05): {'YES' if all_nonsignificant else 'NO — inspect above'}")

    # ── Write output ──────────────────────────────────────────────────────
    fieldnames = [
        "Stim1", "Pseudoword1", "Pseudoword2",
        "Pseudoword2_PTAN", "Pseudoword2_PTAF", "Pseudoword2_OTAN", "Pseudoword2_OTAF",
        "Selected",
    ]
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for c in selected:
            writer.writerow({
                "Stim1": c.stim1, "Pseudoword1": c.pseudoword1, "Pseudoword2": c.pseudoword2,
                "Pseudoword2_PTAN": c.stats["PTAN"], "Pseudoword2_PTAF": c.stats["PTAF"],
                "Pseudoword2_OTAN": c.stats["OTAN"], "Pseudoword2_OTAF": c.stats["OTAF"],
                "Selected": "YES",
            })
        for c in unselected:
            writer.writerow({
                "Stim1": c.stim1, "Pseudoword1": c.pseudoword1, "Pseudoword2": c.pseudoword2,
                "Pseudoword2_PTAN": c.stats["PTAN"], "Pseudoword2_PTAF": c.stats["PTAF"],
                "Pseudoword2_OTAN": c.stats["OTAN"], "Pseudoword2_OTAF": c.stats["OTAF"],
                "Selected": "no",
            })
        writer.writerow({k: "" for k in fieldnames})
        writer.writerow({"Stim1": "Real-word mismatch mean", **{f"Pseudoword2_{m}": round(target_means[m], 4) for m in MEASURES}})
        writer.writerow({"Stim1": "Selected pseudoword mean", **{f"Pseudoword2_{m}": round(selected_means[m], 4) for m in MEASURES}})
        writer.writerow({"Stim1": "Cohen's d", **{f"Pseudoword2_{m}": round(best_d[m], 4) for m in MEASURES}})
        writer.writerow({"Stim1": "t-test p-value", **{f"Pseudoword2_{m}": round(best_p[m], 4) for m in MEASURES}})
        writer.writerow({"Stim1": "Composite score (sum d^2)", "Pseudoword1": round(best_score, 4)})

    print(f"\nWritten → {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Select the Pseudoword2 subset that best matches the real-word "
                     "Mismatch Stim2 set on PTAN/PTAF/OTAN/OTAF."
    )
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", default="mismatch_pseudowords_selected.csv")
    parser.add_argument("--restarts", type=int, default=200)
    parser.add_argument("--steps", type=int, default=4000)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    run(args.input, args.output, args.restarts, args.steps, args.seed)
